### ISSUE TITLE
Add to clojars

### ISSUE THREAD

**Issue by tami5** [babashka/babashka.curl#30]
Hey @borkdude can you please upload babashka.curl to clojars if its possible. Thanks

**Comment by borkdude** [comment]
Done: https://clojars.org/babashka/babashka.curl

**Comment by tami5** [comment]
@borkdude thanks a lot.

**Comment by borkdude** [comment]
@tami5 I'm curious what you are doing with this lib on the JVM. Are you willing to share what you are doing?

**Comment by tami5** [comment]
Currently I'm experimenting for my dotenv profile/configuration management project, and porting this code over https://github.com/tami5/vplayground/blob/master/imgup.v .

Also, since its part of babashka, which I will definitely be using to handle the above stuff, its good to get use it.

@borkdude few week back, I think of seen of project that compiles bb scripts, but don't where I've seen, it would be cool if you have any information about it or confirm that it doesn't exists :D

**Comment by borkdude** [comment]
@tami5 Do you mean this one? https://github.com/MnRA/nativity

**Comment by tami5** [comment]
@borkdude oh yes, thats awesome, the past few day I was looking for it. Thank you
