### ISSUE TITLE
Is there a way to display curl progress information?

### ISSUE THREAD

**Issue by jackdbd** [babashka/babashka.curl#34]
This is not really an issue but a question.

The curl CLI tool shows a progress bar when either `-#` or `--progress-bar` are passed to it. However, this wrapper library uses `--silent`, so no progress information is displayed.

As far as I understood, it's not possible to override this behavior using `:raw-args`. Am I correct?

**Comment by borkdude** [comment]
@jackdbd This is correct, there is no way to replace the default args (currently). The way this library uses curl is more like how you would use clj-http, etc. To make use of curl as a true CLI, I would just shell out to it using babashka.process:

```
user=> (def response (-> (process ["curl" "--progress-bar" "http://ipv4.download.thinkbroadband.com/200MB.zip"] {:out byte-stream :err :inherit}) deref :out))
######################################################################## 100.0%
#'user/response
user=> (type response)
java.io.ByteArrayOutputStream
user=> (count (.toByteArray response))
209715200
user=> (/ 209715200 1024)
204800
user=> (/ 209715200 1024 1024)
200
```
