### ISSUE TITLE
Last set-cookie headers on a page overwrites the ones before

### ISSUE THREAD

**Issue by erikthorselius** [babashka/babashka.curl#43]
If a homepage has multiple `set-cookes` headers it is only the last `set-cookie` is in the response :header map.

**Comment by borkdude** [comment]
@erikthorselius Can you give a more concrete example which allows us to test and fix the problem?

**Comment by borkdude** [comment]
Hato:

https://github.com/gnarroway/hato/blob/7e69c7cf80635fb94c90627daaedb5c8a5584ad0/src/hato/client.clj#L155

Not sure what it does there...

**Comment by borkdude** [comment]
clj-http, same as clj-http-lite: 

https://github.com/dakrone/clj-http/blob/5f0f842f330201cdfbeedcde781bb62cbdd018b8/src/clj_http/core.clj#L33-L35

I guess we would be safe doing the same as people should already be relatively used to this behavior and we would not break anything.

**Comment by borkdude** [comment]
I guess httpkit has the same bug:

https://github.com/http-kit/http-kit/blob/9eac670a71f390a9e988deddfcf3203fa0970de7/src/org/httpkit/client.clj#L34

**Comment by borkdude** [comment]
Let's go ahead with the clj-http/lite approach.

**Comment by erikthorselius** [comment]
Wow you are fast! 

Sorry for my short description and it looks like you figured it out. I tried to get a session cookie from the headers but it was only one set-cookie header. But if I curl the page directly it was two headers and the session was the first so it was overwritten.

**Comment by lispyclouds** [comment]
Sounds good to me too! Would be consistent with the query params impl now 😄

**Comment by borkdude** [comment]
> Would be consistent with the query params impl now 

How's that?

**Comment by lispyclouds** [comment]
Ah yeah I misread the clj-http impl as the way we handle the same named query params by passing a vector of vectors. But now that I read it again its different.
